export enum Country {
    RU = 'Russia',
    USA = 'United States',
    UK = 'United Kingdom',
    FR = 'France',
    DE = 'Germany',
    IT = 'Italy',
    ES = 'Spain',
    CN = 'China',
    JP = 'Japan',
    KR = 'South Korea',
    BR = 'Brazil',
    IN = 'India',
    AU = 'Australia',
    CA = 'Canada',
    MX = 'Mexico',
    AR = 'Argentina',
    CL = 'Chile',
    CO = 'Colombia',
    PE = 'Peru',
    ZA = 'South Africa',
    ID = 'Indonesia',
    TH = 'Thailand',
    VN = 'Vietnam',
    MY = 'Malaysia',
}
